name: Auto Release from version.txt

on:
  push:
    branches:
      - main
    paths:
      - version.txt

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get version from version.txt
        id: get_version
        run: |
          version=$(cat version.txt | tr -d '\n')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Setup git user
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create git tag if not exists
        run: |
          if git rev-parse "refs/tags/${{ steps.get_version.outputs.version }}" >/dev/null 2>&1
          then
            echo "Tag ${{ steps.get_version.outputs.version }} already exists"
          else
            git tag ${{ steps.get_version.outputs.version }}
            git push origin ${{ steps.get_version.outputs.version }}
          fi

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          name: Release ${{ steps.get_version.outputs.version }}
          body: Automated release for version ${{ steps.get_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}