name: Auto Release from version.txt

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - version.txt

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from version.txt
        id: get_version
        run: |
          version=$(awk '{$1=$1};1' version.txt)
          echo "version=$version" >> $GITHUB_OUTPUT
          
      - name: Create or update GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          name: Release ${{ steps.get_version.outputs.version }}
          body: Automated release for version ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.CNV_RELEASE_AUTOMATION }}
