name: Auto Release from version.txt

on:
  push:
    branches:
      - main
    paths:
      - version.txt

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from version.txt
        id: get_version
        run: |
          version=$(awk '{$1=$1};1' version.txt)
          echo "version=$version" >> $GITHUB_OUTPUT

      # - name: Setup git user
        # run: |
          # git config alexandra-valeanu "github-actions"
          # git config valeanualexandra17@gmail.com "github-actions@github.com"

      - name: Force create/update annotated git tag
        run: |
          git tag -fa "${{ steps.get_version.outputs.version }}" -m "Release ${{ steps.get_version.outputs.version }}"
          git push origin -f "${{ steps.get_version.outputs.version }}"

      - name: Create or update GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          name: Release ${{ steps.get_version.outputs.version }}
          body: Automated release for version ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
