name: Trigger cnv-website YAML rebuild

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - version.txt

jobs:
  notify-cnv-booklet:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger cnv-website via repository_dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.CNV_RELEASE_AUTOMATION }}
          repository: CNVPathwayAtlas/cnv-website
          event-type: cnv-data-updated
